### ISSUE TITLE
TODO for loading SpaDES Outputs that are not raster

### ISSUE THREAD

**Issue by see24** [LandSciTech/ROFSim#15]
Is this still needed? 

https://github.com/LandSciTech/ROFSim/blob/21c753c6b8985504cb4f3037c8887e163ac0bd86/load_spades_outputs.R#L175

**Comment by josie-hughes** [comment]
Since we are not currently using any SpaDES outputs that are not rasters, this is not a high priority for fixing. Can leave the TODO note in the code and deal with it if ever it becomes a real problem.
